### ISSUE TITLE
Change the type of the MMDSConfig reference in Swagger API

### ISSUE THREAD

**Issue by zsadeghi** [firecracker-microvm/firecracker#1843]
Hi!

Currently, the swagger API definition for the MMDSConfig endpoint reads as:

```yaml
        - name: body
          in: body
          description: The MMDS configuration as JSON.
          required: true
          schema:
            type: "#/definitions/MmdsConfig"
```

Since the type is not a built-in, this has to change to `$ref`. I will open a pull request alongside this issue.

Thanks!
